In [165]:
import pandas as pd 
data = { 
"RollNo": [101, 102, 103, 104, 105, 106, 107, 108], 
"Name": [ 
    "Amit", "Neha", "Rahul", "Priya",  
    "Rohan", "Kavya", "Arjun", "Simran" 
], 
"Department": [ 
    "BCA", "BCA", "MCA", "BCA", 
    "MCA", "MCA", "BCA", "MCA" 
], 
"Age": [20, 21, 22, 20, 23, 22, 21, 24], 
"Marks": [85, 92, 67, 78, 88, 95, 55, 73] 
} 
df = pd.DataFrame(data)

In [90]:
# Q1. Display the complete DataFrame. 
print(df)

   RollNo    Name Department  Age  Marks
0     101    Amit        BCA   20     85
1     102    Neha        BCA   21     92
2     103   Rahul        MCA   22     67
3     104   Priya        BCA   20     78
4     105   Rohan        MCA   23     88
5     106   Kavya        MCA   22     95
6     107   Arjun        BCA   21     55
7     108  Simran        MCA   24     73

In [95]:
# Q2. Display the first 3 records. 
print(df.head(3))

   RollNo   Name Department  Age  Marks
0     101   Amit        BCA   20     85
1     102   Neha        BCA   21     92
2     103  Rahul        MCA   22     67

In [98]:
# Q3. Display the last 2 records. 
print(df.tail(2))

   RollNo    Name Department  Age  Marks
6     107   Arjun        BCA   21     55
7     108  Simran        MCA   24     73

In [99]:
# Q4. Find the number of rows and columns
print(df.shape)

(8, 5)

In [100]:
# Q5. Display all column names. 
print(df.columns)

Index(['RollNo', 'Name', 'Department', 'Age', 'Marks'], dtype='object')

In [107]:
# Q6. Display the data types of all columns.
print(df.dtypes)

RollNo         int64
Name          object
Department    object
Age            int64
Marks          int64
dtype: object

In [110]:
# Q7. Display only the Name column. 
df["Name"]

0      Amit
1      Neha
2     Rahul
3     Priya
4     Rohan
5     Kavya
6     Arjun
7    Simran
Name: Name, dtype: object

In [114]:
# Q8. Display Name and Marks. 
df[["Name","Marks"]]

     Name  Marks
0    Amit     85
1    Neha     92
2   Rahul     67
3   Priya     78
4   Rohan     88
5   Kavya     95
6   Arjun     55
7  Simran     73

In [117]:
# Q9. Display students who scored more than 80. 
print(df[df["Marks"]>80])

   RollNo   Name Department  Age  Marks
0     101   Amit        BCA   20     85
1     102   Neha        BCA   21     92
4     105  Rohan        MCA   23     88
5     106  Kavya        MCA   22     95

In [ ]:
# Q10. Display students who scored less than 70. 

# Homework

In [125]:
# Q11. Display students whose marks are between 70 and 90.

# print(df)
print(df [(df["Marks"]>=70)  &  (df["Marks"]<=90)] )

   RollNo    Name Department  Age  Marks
0     101    Amit        BCA   20     85
3     104   Priya        BCA   20     78
4     105   Rohan        MCA   23     88
7     108  Simran        MCA   24     73

In [127]:
# Q12. Display students belonging to the BCA department.
print(df[df["Department"]=="BCA"])

   RollNo   Name Department  Age  Marks
0     101   Amit        BCA   20     85
1     102   Neha        BCA   21     92
3     104  Priya        BCA   20     78
6     107  Arjun        BCA   21     55

In [28]:
# Q13. Display MCA students who scored more than 80.

# Homework

In [131]:
# Q14. Display students whose age is greater than 21.

print(df[df["Age"]>21]["Age"])

2    22
4    23
5    22
7    24
Name: Age, dtype: int64

In [133]:
# Q15. Calculate the average marks.
print(df["Marks"].mean())

79.125

In [134]:
# Q16. Find the maximum marks. 
# Q17. Find the minimum marks. 
print(df["Marks"].max())
print(df["Marks"].min())

95
55

In [143]:
# Q19. Find how many students scored above 75. 

v = df["Marks"]>75
v.sum()

5

In [60]:
# Q20. Find the average marks of BCA students.

# HomeWork

In [155]:
# Q22. Find the highest-scoring student.

allMarks = df["Marks"]
maxMarks = df["Marks"].max()
print(
    df[allMarks == maxMarks]
)

   RollNo   Name Department  Age  Marks
5     106  Kavya        MCA   22     95

In [167]:
# Q23. Add a new column called Bonus and give every student 5 marks.
df
df["Bonus"] = 5
print(df)

   RollNo    Name Department  Age  Marks  Bonus
0     101    Amit        BCA   20     85      5
1     102    Neha        BCA   21     92      5
2     103   Rahul        MCA   22     67      5
3     104   Priya        BCA   20     78      5
4     105   Rohan        MCA   23     88      5
5     106   Kavya        MCA   22     95      5
6     107   Arjun        BCA   21     55      5
7     108  Simran        MCA   24     73      5

In [168]:
# Q24. Create a FinalMarks column: 
# FinalMarks = Marks + Bonus 

df["finalMarks"] = df["Marks"] + df["Bonus"]

In [171]:
# Q25. Create a Result column: 
# Marks >= 40 → Pass 
# Marks < 40  → Fail 

import numpy as np
df["Result"] = np.where(df["Marks"]>=90 ,"Pass" ,"Fail")
df

   RollNo    Name Department  Age  Marks  Bonus  finalMarks Result
0     101    Amit        BCA   20     85      5          90   Fail
1     102    Neha        BCA   21     92      5          97   Pass
2     103   Rahul        MCA   22     67      5          72   Fail
3     104   Priya        BCA   20     78      5          83   Fail
4     105   Rohan        MCA   23     88      5          93   Fail
5     106   Kavya        MCA   22     95      5         100   Pass
6     107   Arjun        BCA   21     55      5          60   Fail
7     108  Simran        MCA   24     73      5          78   Fail

In [ ]:
# Q26. Create a Grade column using: 
# 90 or above → A+ 
# 80–89       → A 
# 70–79       → B 
# 60–69       → C 
# Below 60    → D

# Home work

# grade = []
# grade.append("A+")
 


# df["Grade"] = Grade

In [174]:
# Q27. Sort students according to marks from highest to lowest. 
df = df.sort_values(by="Marks" , ascending  = False)
print(df)

   RollNo    Name Department  Age  Marks  Bonus  finalMarks Result
5     106   Kavya        MCA   22     95      5         100   Pass
1     102    Neha        BCA   21     92      5          97   Pass
4     105   Rohan        MCA   23     88      5          93   Fail
0     101    Amit        BCA   20     85      5          90   Fail
3     104   Priya        BCA   20     78      5          83   Fail
7     108  Simran        MCA   24     73      5          78   Fail
2     103   Rahul        MCA   22     67      5          72   Fail
6     107   Arjun        BCA   21     55      5          60   Fail

In [79]:
# Q28. Display the top 3 students. 
# Hint: 
# df.nlargest(3, "Marks") 

# Homework

In [ ]:
# Q29. Add a Rank column based on marks. 
# Hint: 


# df["Rank"] = df["Marks"].rank( 
# ascending=False 
# )

In [184]:
# Q30. Find the number of students in each department.


# v = df.groupby("Department")["Name"].count()
# print(v)

# print(df)
# df.groupby("Department")["Marks"].max()

# category ,
# konse column pr operation krna hai,
# kya operation krna hai

Department
BCA    4
MCA    4
Name: Name, dtype: int64

In [185]:
# Q31. Find the average marks of each department. 

df.groupby("Department")["Marks"].mean()

Department
BCA    77.50
MCA    80.75
Name: Marks, dtype: float64

In [ ]:
# Q32. Find the maximum marks in each department. 
# Q33. Find the minimum marks in each department.

In [189]:
# Q34 . check min max mean together

df.groupby("Department")["Marks"].agg(
    ["min" ,"max" ,"mean"]
)

            min  max   mean
Department
BCA          55   92  77.50
MCA          67   95  80.75

In [194]:
# Export final report  read_csv and  to_excel

print(df)
df.to_excel("C:\\Users\\Asus\\OneDrive\\Desktop\\data.xlsx")

   RollNo    Name Department  Age  Marks  Bonus  finalMarks Result
5     106   Kavya        MCA   22     95      5         100   Pass
1     102    Neha        BCA   21     92      5          97   Pass
4     105   Rohan        MCA   23     88      5          93   Fail
0     101    Amit        BCA   20     85      5          90   Fail
3     104   Priya        BCA   20     78      5          83   Fail
7     108  Simran        MCA   24     73      5          78   Fail
2     103   Rahul        MCA   22     67      5          72   Fail
6     107   Arjun        BCA   21     55      5          60   Fail

In [87]:
# Q35 : - A 1D labelst Structure in pandas is called? Series

In [ ]:
# Q36 : - data Cleaning : - 
   # Drop Na 
   # marks columns repalce by 0 

# Homework