In [17]:
import pandas as pd
l = [1,2,3,4,5]
s1 = pd.Series(l , index=["a","b","c","d","e"] )
print(s1)
print(s1['d'])

a    1
b    2
c    3
d    4
e    5
dtype: int64
4

In [34]:
import pandas as pd
l = [1,2,3,4,5]
s = pd.Series(l , index=['a','b','c','d','e'])
print(s)
print(s['c'])

a    1
b    2
c    3
d    4
e    5
dtype: int64
3

In [43]:
di = {
    "name":["harshu","nasi"],
    "roll":[1,2]
}
df1 = pd.DataFrame(di ,index=['a','b'])


l = [
    ["nasi",1],
    ["harshu",2],
    ["raaz",3]
]

df2 = pd.DataFrame(l , index=['a',"b","c"] , columns = ["x","y"])
print(df1)
print()
print(df2)

# Series
# () -> round Brackets

# DataFrame
# () -> round Brackets

# index = []
# columns = []

# output predict

     name  roll
a  harshu     1
b    nasi     2

        x  y
a    nasi  1
b  harshu  2
c    raaz  3

In [49]:
# Create a Series using NDarray 
import numpy as np
import pandas as pd
arr = np.array([1,2,3,45])
s = pd.Series(arr)
print(s)


mat = [
    [1,2,3],
    [4,5,6]
]
brr = np.array(mat)
df = pd.DataFrame(brr ,index=["a","b"] , columns = ["z","x","y"] )
print(df)

0     1
1     2
2     3
3    45
dtype: int32
   z  x  y
a  1  2  3
b  4  5  6

In [64]:
# Create a Series using NDarray 
import numpy as np
import pandas as pd
arr = np.array([1,2,3,4,5,6,7,8,9])
s = pd.Series(arr)
# print(s)
# print(s.head())



print(df)
print(df.index)
print(df.columns)

   z  x  y
a  1  2  3
b  4  5  6
Index(['a', 'b'], dtype='object')
Index(['z', 'x', 'y'], dtype='object')

In [85]:
import pandas as pd
di = {
    "name":["harshu","nasi" ,"raaz","vansh"],
    "roll":[1,2,3,4],
    "age":[16,17,19,20]
}
df = pd.DataFrame(di )
print(df)
print()
print(df[["age" ]])
print(df.loc[1:3 , ["roll"]])
print()
print(df.loc[0])

     name  roll  age
0  harshu     1   16
1    nasi     2   17
2    raaz     3   19
3   vansh     4   20

   age
0   16
1   17
2   19
3   20
   roll
1     2
2     3
3     4

name    harshu
roll         1
age         16
Name: 0, dtype: object

In [95]:
print(df)
print()
# print(df[df["age"]>17])
# df[df["age"]>17]

     name  roll  age
0  harshu     1   16
1    nasi     2   17
2    raaz     3   19
3   vansh     4   20

    name  roll  age
2   raaz     3   19
3  vansh     4   20

    name  roll  age
2   raaz     3   19
3  vansh     4   20

In [154]:
# Data Cleanup
di = {
    "name":["nasirulla","harshu","raaz"],
    "age":[16,None,19],
    "roll":[None , 2 , 3]
}
df = pd.DataFrame(di)
print(df)


# df.isnull().sum()
df["age"] = df["age"].fillna(df["age"].mean())
df = df.fillna(0)
print(df)

        name   age  roll
0  nasirulla  16.0   NaN
1     harshu   NaN   2.0
2       raaz  19.0   3.0
        name   age  roll
0  nasirulla  16.0   0.0
1     harshu  17.5   2.0
2       raaz  19.0   3.0

In [160]:
# Drop
# print(df)
# df.drop(2 , inplace = True)
# print(df)

# Delete a row of dataFrame which roll no. have == 3

df.drop(df[df["roll"]==3].index)

        name   age  roll
0  nasirulla  16.0   0.0
1     harshu  17.5   2.0